version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - .:/var/www/html
            - ./ssl:/etc/nginx/ssl # /!\ il faut partager le dossier des certificats
        ports:
            - "443:443" # Port HTTPS
            - "8080:80" # Port Http
        networks:
            - laravel

volumes:
    mysql-data:

networks:
    laravel:
