version: '3.8'

services:
    app:
        env_file:
            -   .env
        environment:
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html

    nginx:
        image: nginx:1.27.2-alpine3.20
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: zoo_arcadia
            MYSQL_DATABASE: zoo_arcadia
            MYSQL_USER: isabelle
            MYSQL_PASSWORD: zoo_arcadia
        ports:
            - "3306:3306"
    mongo:
        image: mongo:8
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: arcadia
            MONGO_INITDB_ROOT_PASSWORD: arcadia
        volumes:
            - mongo_data:/data/db
            - ./api/database/init/init-zoo-arcadia.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - "27027:27017"
volumes:
    mongo_data:
