<?php

return [
    'zoo' => [
        [
            'id' => '1',
            'name' => 'Arcadia',
            'description' => "Bienvenue à Arcadia, un zoo unique en son genre situé tout près de la légendaire forêt de Brocéliande en Bretagne, en France. Fondé en 1960, Arcadia vous invite à un voyage fascinant au cœur de la faune japonaise. Découvrez une diversité exceptionnelle d'animaux originaires du Japon dans un cadre enchanteur et préservé.",
        ],
    ],
    'users' => [
        [
            'id' => '1',
            'zoo_id' => '1',
            'name' => 'José Admin',
            'email' => 'joseadmin@gmail.com',
            'password' => '123456789aze',
            'role' => 'admin',
        ],
        [
            'id' => '2',
            'zoo_id' => '1',
            'name' => 'Josette Veterinarian',
            'email' => 'josetteveterinarian@gmail.com',
            'password' => '123456789aze',
            'role' => 'veterinarian',
        ],
        [
            'id' => '3',
            'zoo_id' => '1',
            'name' => 'Joseph Employee',
            'email' => 'josephemployee@gmail.com',
            'password' => '123456789aze',
            'role' => 'employee',
        ],
    ],
    'habitats' => [
        [
            'id' => '1',
            'zoo_id' => '1',
            'name' => 'Savane',
            'description' => "La savane est une vaste étendue de prairies parsemées d'arbres clairsemés, caractérisée par un climat saisonnier avec des périodes de pluies et de sécheresses. Elle abrite une grande diversité d'animaux, tels que les lions, éléphants et antilopes, adaptés à ce milieu ouvert.",
            'image' => 'savane.jpg',
        ],
        [
            'id' => '2',
            'zoo_id' => '1',
            'name' => 'Jungle',
            'description' => "La jungle est une forêt dense et humide, dominée par une végétation luxuriante, avec un climat tropical chaud et des pluies abondantes. Elle abrite une biodiversité riche, incluant des espèces comme les singes, jaguars et oiseaux exotiques, vivant dans un environnement ombragé et touffu.",
            'image' => 'jungle.jpg',
        ],
        [
            'id' => '3',
            'zoo_id' => '1',
            'name' => 'Marais',
            'description' => "Les marais sont des zones humides où l'eau stagnante recouvre le sol, créant un écosystème riche en végétation aquatique comme les roseaux. Ils abritent une faune diversifiée, incluant des oiseaux, amphibiens, et reptiles, adaptés à cet environnement saturé d'eau.",
            'image' => 'marais.jpg'
        ],
    ],
    'services' => [
        [
            'id' => '1',
            'zoo_id' => '1',
            'name' => 'Restauration',
            'description' => "Situé au cœur du zoo, offrant une pause gourmande idéale pour toute la famille. Avec un menu varié allant des sandwichs savoureux aux salades fraîches, il y en a pour tous les goûts. Les enfants adoreront les menus thématiques inspirés des animaux du parc, tandis que les adultes pourront se détendre sur la terrasse ombragée. Le Croc'zoo est l'endroit parfait pour recharger les batteries avant de poursuivre la découverte des merveilles du zoo.",
            'image' => 'restaurant-exterior.jpg',
        ],
        [
            'id' => '2',
            'zoo_id' => '1',
            'name' => 'Visite guidée',
            'description' => "Découvrez les merveilles du zoo d'Arcadia lors d'une visite guidée enrichissante qui vous plonge au cœur du monde animal. Accompagné d'un guide expert, explorez les habitats naturels recréés et apprenez des anecdotes fascinantes sur chaque espèce. Les enfants comme les adultes seront émerveillés par la diversité des animaux et les histoires captivantes qui les entourent. Cette aventure éducative et divertissante vous offre une expérience unique, enrichissant votre visite d'une compréhension plus profonde de la faune et de la flore. Ne manquez pas cette occasion de voir de près des créatures rares et exotiques tout en profitant d'un moment inoubliable en famille ou entre amis.",
            'image' => 'zoo-visite-asie.jpg',
        ],
        [
            'id' => '3',
            'zoo_id' => '1',
            'name' => 'Visite en petit train',
            'description' => "Embarquez à bord du petit train touristique du zoo d'Arcadia pour une visite inoubliable à travers les différents mondes animaliers. Ce voyage confortable vous permet de découvrir les habitats des animaux tout en profitant de commentaires fascinants sur les espèces et leur mode de vie. Idéal pour les familles, le petit train offre une vue panoramique sur les zones les plus emblématiques du parc. Les enfants seront enchantés par cette balade ludique, tandis que les adultes apprécieront le rythme détendu de la visite. Une manière amusante et éducative de parcourir le zoo sans effort !",
            'image' => 'train-touristique.jpg',
        ],
    ],
    'animals' => [
        [
            'id' => '1',
            'habitat_id' => '2',
            'name' => 'Loulou et Louloute',
            'breed' => 'Macaque',
            'image' => 'macaques.jpg',
            'description' => "Petits singes, macaques du Japon dans son onsen dans l'habitat de la jungle.",
        ],
        [
            'id' => '2',
            'habitat_id' => '3',
            'name' => 'Tutu',
            'breed' => 'Tortue',
            'image' => 'turtle-jp.jpg',
            'description' => "Tortue du Japon, dans l'habitat des marais",
        ],
        [
            'id' => '3',
            'habitat_id' => '1',
            'name' => 'Tori',
            'breed' => 'Renard',
            'image' => 'renard.jpg',
            'description' => "Petit renard du Japon dans l'habitat de la savane",
        ],
        [
            'id' => '4',
            'habitat_id' => '2',
            'name' => 'Baloo',
            'breed' => 'Ours noir',
            'image' => 'ours-noir-jp.jpg',
            'description' => "Ours noir à collier, est un ours japonais dans l'habitat de la jungle.",
        ],
        [
            'id' => '5',
            'habitat_id' => '1',
            'name' => 'Panpan',
            'breed' => 'Lapin',
            'image' => 'rabbit-jp.jpg',
            'description' => "Lapin japonais, aux jolies couleurs dans l'habitat de la savane",
        ],
        [
            'id' => '6',
            'habitat_id' => '1',
            'name' => 'Bambi',
            'breed' => 'Biche',
            'image' => 'biche.jpg',
            'description' => "Biche japonaise, dans l'habitat de la savane",
        ],
        [
            'id' => '7',
            'habitat_id' => '3',
            'name' => 'Kaa',
            'breed' => 'Serpent',
            'image' => 'habu-d-okinawa.jpg',
            'description' => "Habu d'Okinawa, ce serpent du Japon dans l'habitat des marais.",
        ],
        [
            'id' => '8',
            'habitat_id' => '2',
            'name' => 'Titan',
            'breed' => 'Shiba Inu',
            'image' => 'shiba-inu.webp',
            'description' => "Magnifique Shiba Inu du Japon dans l'habitat de la jungle."
        ],
    ],
    'foods' => [
        [
            'id' => '1',
            'name' => 'Fruits',
        ],
        [
            'id' => '2',
            'name' => 'Salade',
        ],
        [
            'id' => '3',
            'name' => 'Viande',
        ],
        [
            'id' => '4',
            'name' => 'Poisson',
        ],
        [
            'id' => '5',
            'name' => 'Écorces',
        ],
        [
            'id' => '6',
            'name' => 'Souris',
        ],
        [
            'id' => '7',
            'name' => 'Croquettes',
        ]
    ],
    'foods_consum' => [
        [
            'id' => '1',
            'food_id' => '1',
            'animal_id' => '1',
            'quantity' => '750',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '2',
            'food_id' => '2',
            'animal_id' => '2',
            'quantity' => '600',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '3',
            'food_id' => '3',
            'animal_id' => '3',
            'quantity' => '370',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '4',
            'food_id' => '4',
            'animal_id' => '4',
            'quantity' => '1000',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '5',
            'food_id' => '2',
            'animal_id' => '5',
            'quantity' => '650',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '6',
            'food_id' => '5',
            'animal_id' => '6',
            'quantity' => '300',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '7',
            'food_id' => '6',
            'animal_id' => '7',
            'quantity' => '400',
            'unit' => 'g',
            'user_id' => '3',
        ],
        [
            'id' => '8',
            'food_id' => '7',
            'animal_id' => '8',
            'quantity' => '800',
            'unit' => 'g',
            'user_id' => '3',
        ],
    ],
    'veterinarian_reports' => [
        [
            'id' => '1',
            'animal_id' => '1',
            'animal_state' => 'En bonne santé',
            'food_consum_id' => '1',
            'content' => "Le couple de macaques ont été examinés ce matin et présentent un bon état général.",
            'user_id' => '2',
        ],
        [
            'id' => '2',
            'animal_id' => '2',
            'animal_state' => 'À surveiller',
            'food_consum_id' => '2',
            'content' => "Tutu la tortue montre une amélioration significative après son traitement contre l'infection urinaire.",
            'user_id' => '2',
        ],
        [
            'id' => '3',
            'animal_id' => '3',
            'animal_state' => 'À surveiller',
            'food_consum_id' => '3',
            'content' => "Tori a une légère inflammation des gencives, mais son état général reste stable.",
            'user_id' => '2',
        ],
        [
            'id' => '4',
            'animal_id' => '4',
            'animal_state' => 'En bonne santé',
            'food_consum_id' => '4',
            'content' => "Baloo est en bonne santé, avec une carapace solide et une alimentation équilibrée.",
            'user_id' => '2',
        ],
        [
            'id' => '5',
            'animal_id' => '5',
            'animal_state' => 'Signes de vieillesse',
            'food_consum_id' => '5',
            'content' => "Panpan montre des signes de vieillesse, notamment un pelage légèrement terne et une activité réduite, mais reste en bonne santé générale.",
            'user_id' => '2',
        ],
        [
            'id' => '6',
            'animal_id' => '6',
            'animal_state' => 'En bonne santé',
            'food_consum_id' => '6',
            'content' => "Bambi est en pleine forme, avec un poids stable et une activité normale.",
            'user_id' => '2',
        ],
        [
            'id' => '7',
            'animal_id' => '7',
            'animal_state' => 'En bonne santé',
            'food_consum_id' => '7',
            'content' => "Kaa semble en bonne santé générale, bien hydraté et sans signe de mue problématique.",
            'user_id' => '2',
        ],
        [
            'id' => '8',
            'animal_id' => '8',
            'animal_state' => 'En bonne santé',
            'food_consum_id' => '8',
            'content' => "Titan présente un excellent état de santé général, avec une musculature bien développée et des articulations souples.",
            'user_id' => '2',
        ],

    ],
    'openings' => [
        [
            'id' => '1',
            'zoo_id' => '1',
            'day_open' => 'Lundi',
            'hour_open' => '14:00',
            'hour_close' => '18:00',
        ],
        [
            'id' => '2',
            'zoo_id' => '1',
            'day_open' => 'Mardi',
            'hour_open' => '11:00',
            'hour_close' => '17:00',
        ],
        [
            'id' => '3',
            'zoo_id' => '1',
            'day_open' => 'Mercredi',
            'hour_open' => '10:00',
            'hour_close' => '19:00',
        ],
        [
            'id' => '4',
            'zoo_id' => '1',
            'day_open' => 'Jeudi',
            'hour_open' => '14:00',
            'hour_close' => '18:30',
        ],
        [
            'id' => '5',
            'zoo_id' => '1',
            'day_open' => 'Vendredi',
            'hour_open' => '11:00',
            'hour_close' => '19:00',
        ],
        [
            'id' => '6',
            'zoo_id' => '1',
            'day_open' => 'Samedi',
            'hour_open' => '10:00',
            'hour_close' => '19:00',
        ],
        [
            'id' => '7',
            'zoo_id' => '1',
            'day_open' => 'Dimanche',
            'hour_open' => '10:00',
            'hour_close' => '19:00',
        ],
    ],
    'reviews' => [
        [
            'id' => '1',
            'zoo_id' => '1',
            'content' => "Le zoo Arcadia est un véritable bijou caché en Bretagne. La proximité de la forêt de Brocéliande ajoute un charme magique à l'endroit. Les animaux sont bien soignés, et le personnel est très accueillant. J'ai particulièrement apprécié l'enclos des loups, c'était fascinant de les observer dans un environnement aussi naturel. Un lieu parfait pour une sortie en famille.",
            'status' => 'pending',
            'author' => 'Alfred Lecoq',
            'rating' => '5',
        ],
        [
            'id' => '2',
            'zoo_id' => '1',
            'content' => "J'ai adoré ma visite au zoo Arcadia ! Le parc est bien aménagé et spacieux, ce qui permet aux animaux de vivre dans des habitats qui ressemblent à leur milieu naturel. Les informations fournies sur chaque espèce étaient complètes, et j'ai appris beaucoup de choses. Petit plus : les sentiers bordés d'arbres rappellent la forêt de Brocéliande toute proche, c'est vraiment dépaysant !",
            'status' => 'pending',
            'author' => 'Brume Sauvage',
            'rating' => '4',
        ],
        [
            'id' => '3',
            'zoo_id' => '1',
            'content' => "Un peu déçu par ma visite au zoo Arcadia. Les animaux semblaient parfois un peu apathiques, et certains enclos manquaient d'entretien. Par contre, j'ai beaucoup aimé la proximité avec la nature environnante, surtout avec la légendaire forêt de Brocéliande. Peut-être que le zoo pourrait bénéficier de quelques rénovations et améliorations.",
            'status' => 'rejected',
            'author' => 'Toto Zero',
            'rating' => '3',
        ],
        [
            'id' => '4',
            'zoo_id' => '1',
            'content' => "Un endroit incroyable pour les amoureux de la nature et des animaux ! Le zoo Arcadia met l'accent sur la conservation et le bien-être animal, ce qui est vraiment appréciable. Les activités pédagogiques pour les enfants sont top, et la proximité avec Brocéliande apporte une touche mystique à la visite. Je recommande à 100 % pour une journée de détente et de découverte.",
            'status' => 'validated',
            'author' => 'Jane Doe',
            'rating' => '4',
        ],
        [
            'id' => '5',
            'zoo_id' => '1',
            'content' => "Le zoo est charmant et assez bien entretenu, mais ce qui m'a le plus marqué, c'est l'atmosphère magique des environs. La forêt de Brocéliande toute proche rend la visite encore plus spéciale, presque féerique. Le zoo propose aussi des animations autour de la légende arthurienne, ce qui a beaucoup plu à mes enfants. Une belle expérience à renouveler !",
            'status' => 'validated',
            'author' => 'Jade Choupi',
            'rating' => '5',
        ],
    ],
];
